<string> ::= <letter>|<letter><string>

<letter> ::= <lower_vowel>|<upper_vowel>|<lower_consonant>|<upper_consonant>|<symbols>

<lower_vowel> ::= a|e|i|o|u|y

<upper_vowel> ::= A|E|I|O|U|Y

<lower_consonant> ::= q|w|r|t|p|s|d|f|g|h|j|k|l|z|x|c|v|b|n|m

<upper_consonant> ::= Q|W|R|T|P|S|D|F|G|H|J|K|L|Z|X|C|V|B|N|M

<symbols>         ::= .|,|?|!|-|" "